import img1 from './profilePics/img1.jpg';
import img2 from './profilePics/img2.jpg';
import img3 from './profilePics/img3.jpg';
import img4 from './profilePics/img4.jpg';
import img5 from './profilePics/img5.jpg';
import img6 from './profilePics/img6.jpg';

export const details = [
    {
        "id": 1,
        "name": "Snehal Chodankar",
        "designation": "Student",
        "email": "mailto:snehalchodankar91@gmail.com",
        "mobile": "tel:9284832649",
        "linkedin": "https://www.linkedin.com/in/snehal-chodankar-372520165/",
        "github": "https://github.com/SnehalChodankar",
        "insta": "https://www.instagram.com/SnehalChodankar/",
        "wiseWords": "In life, you always have an opportunity to do something, you just have to grab it.",
        "image": img2,
        "interests": ["WebDev", "Sketching", "Photography"],
    },
    {
        "id": 2,
        "name": "Pooja Raghmode",
        "designation": "Student",
        "email": "mailto:poojaraghmode05@gmail.com",
        "mobile": "tel:8459650830",
        "linkedin": "https://www.linkedin.com/in/raghmode/",
        "github": "https://github.com/poojaraghmode",
        "insta": "https://www.instagram.com/pooja._.05/",
        "wiseWords": "Somewhere inside of all of us is the power to change the world.",
        "image": img3,
        "interests": ["Sketching", "Mathematics"],
    },
    {
        "id": 3,
        "name": "Urvesh Vernekar",
        "designation": "Student",
        "email": "mailto:urveshvernekar8@gmail.com",
        "mobile": "tel:9975286188",
        "linkedin": "https://www.linkedin.com/in/urvesh-vernekar-04409b188/",
        "github": "https://github.com/UrveshVernekar",
        "insta": "https://www.instagram.com/avenger4real/",
        "wiseWords": "Freedom is all but a big lie, no one's really free in this world, all are slaves to someone or something.",
        "image": img1,
        "interests": ["Web Dev", "Android App Development"],
    },
    {
        "id": 4,
        "name": "Sidharth Kumar",
        "designation": "Student",
        "email": "mailto:sidharth17it53@gmail.com",
        "mobile": "tel:7722082259",
        "linkedin": "https://www.linkedin.com/in/sidharth-kumar-44a50418b/",
        "github": "https://github.com/sidharth274",
        "insta": "https://www.instagram.com/sidhar.th/",
        "wiseWords": "Shift + Delete bad memories.",
        "image": img4,
        "interests": ["Motorcycles"],
    },
    {
        "id": 5,
        "name": "Arundhati Kanekar",
        "designation": "Student",
        "email": "mailto:arunkanekar18@gmail.com",
        "mobile": "tel:9423886767",
        "linkedin": "https://www.linkedin.com/in/arundhati-kanekar-47650418b/",
        "github": "https://github.com/Arundhati18",
        "insta": "https://www.instagram.com/ar.undhati/",
        "wiseWords": "To live a creative life, we must lose our fear of being wrong.",
        "image": img5,
        "interests": ["Painting", "Dancing", "Singing"],
    },
    {
        "id": 6,
        "name": "Simran Beig ",
        "designation": "Student ",
        "email": "mailto:simranbeig.work@gmail.com",
        "mobile": "tel:8788297073",
        "linkedin": "https://www.linkedin.com/in/simran-beig-347ab71b5/",
        "github": "https://github.com/simzee",
        "insta": "https://www.instagram.com/simmiee14/",
        "wiseWords": "Everyday brings a new ray of hope.",
        "image": img6,
        "interests": ["Crafting", "Dancing", "Poetry"],
    }
];
